---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sctp-network-policy
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: sctpclient
      toPorts:
        - ports:
            - port: "9999"
              protocol: SCTP
