---
apiVersion: v1
kind: Service
metadata:
  name: deathstar-2
  labels:
    color: blue
spec:
  type: ClusterIP
  externalIPs:
    - 12.0.0.101
  ports:
    - port: 80
  selector:
    org: empire
    class: deathstar
